### ISSUE TITLE
 FATAL EXCEPTION: GLThread 742

### ISSUE THREAD

**Issue by DiMiTriFrog** [SureshkumarKV/PureVideoLiveWallpaper#1]
The library works perfectly with Android Emulators, but if I install the app in other terminals how a Motorola X or Wiko the WallpaperService crash with this error:

 Process: in.sureshkumarkv.purevideolivewallpaper, PID: 11676
    java.lang.RuntimeException: Error creating shader.
        at in.sureshkumarkv.renderlib.GLUtil.compileShader(GLUtil.java:91)
        at in.sureshkumarkv.renderlib.RbShader.upload(RbShader.java:130)
        at in.sureshkumarkv.renderlib.GLUtil.uploadOrUnloadAll(GLUtil.java:49)
        at in.sureshkumarkv.renderlib.RbInstance$2.onSurfaceCreated(RbInstance.java:97)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1503)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

No line code error, the error is only in library of GLT.

Please help me.

**Comment by nguyenvancuongit** [comment]
@SureshkumarKV will not you support this issue, please?
